//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmiOperationManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmiOperationManagement.Resources.SystemResource", typeof(SystemResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        public static string User_Action_Add {
            get {
                return ResourceManager.GetString("User_Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá.
        /// </summary>
        public static string User_Action_Delete {
            get {
                return ResourceManager.GetString("User_Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string User_Action_Login {
            get {
                return ResourceManager.GetString("User_Action_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát khỏi chương trình.
        /// </summary>
        public static string User_Action_LogOut {
            get {
                return ResourceManager.GetString("User_Action_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In ấn.
        /// </summary>
        public static string User_Action_Print {
            get {
                return ResourceManager.GetString("User_Action_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi lệnh.
        /// </summary>
        public static string User_Action_Send {
            get {
                return ResourceManager.GetString("User_Action_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dừng hoạt động.
        /// </summary>
        public static string User_Action_Status_Disable {
            get {
                return ResourceManager.GetString("User_Action_Status_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạt động.
        /// </summary>
        public static string User_Action_Status_Enable {
            get {
                return ResourceManager.GetString("User_Action_Status_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        public static string User_Action_Update {
            get {
                return ResourceManager.GetString("User_Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        public static string User_Action_View {
            get {
                return ResourceManager.GetString("User_Action_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối gateway.
        /// </summary>
        public static string UserFunction_Action_Connect_Gateway {
            get {
                return ResourceManager.GetString("UserFunction_Action_Connect_Gateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngắt kết nối gateway.
        /// </summary>
        public static string UserFunction_Action_Connect_Gateway_Disconnect {
            get {
                return ResourceManager.GetString("UserFunction_Action_Connect_Gateway_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabChangePassword.
        /// </summary>
        public static string UserFunction_ChangePassword {
            get {
                return ResourceManager.GetString("UserFunction_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mnDcuController.
        /// </summary>
        public static string UserFunction_Controller {
            get {
                return ResourceManager.GetString("UserFunction_Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới khách hàng.
        /// </summary>
        public static string UserFunction_CreateCustomer {
            get {
                return ResourceManager.GetString("UserFunction_CreateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới DCU.
        /// </summary>
        public static string UserFunction_CreateDcu {
            get {
                return ResourceManager.GetString("UserFunction_CreateDcu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới điểm đo.
        /// </summary>
        public static string UserFunction_CreateMeasurementPoint {
            get {
                return ResourceManager.GetString("UserFunction_CreateMeasurementPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới công tơ.
        /// </summary>
        public static string UserFunction_CreateMeter {
            get {
                return ResourceManager.GetString("UserFunction_CreateMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnCustomerList.
        /// </summary>
        public static string UserFunction_CustomerList {
            get {
                return ResourceManager.GetString("UserFunction_CustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mnDcuController.
        /// </summary>
        public static string UserFunction_DcuController {
            get {
                return ResourceManager.GetString("UserFunction_DcuController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý modem.
        /// </summary>
        public static string UserFunction_DcuList {
            get {
                return ResourceManager.GetString("UserFunction_DcuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnDeployHistories.
        /// </summary>
        public static string UserFunction_DeployHistories {
            get {
                return ResourceManager.GetString("UserFunction_DeployHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mnDeployment.
        /// </summary>
        public static string UserFunction_Deployment {
            get {
                return ResourceManager.GetString("UserFunction_Deployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabErrorDefine.
        /// </summary>
        public static string UserFunction_ErrorDefine {
            get {
                return ResourceManager.GetString("UserFunction_ErrorDefine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnErrorModem.
        /// </summary>
        public static string UserFunction_ErrorModem {
            get {
                return ResourceManager.GetString("UserFunction_ErrorModem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnFixStep.
        /// </summary>
        public static string UserFunction_FixBugeStep {
            get {
                return ResourceManager.GetString("UserFunction_FixBugeStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu lấy bản tin từ hệ thống.
        /// </summary>
        public static string UserFunction_GetLostMessage {
            get {
                return ResourceManager.GetString("UserFunction_GetLostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý điểm đo.
        /// </summary>
        public static string UserFunction_MeasurementPointList {
            get {
                return ResourceManager.GetString("UserFunction_MeasurementPointList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMeasurementPoitMessageError.
        /// </summary>
        public static string UserFunction_MeasurementPoitMessageError {
            get {
                return ResourceManager.GetString("UserFunction_MeasurementPoitMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMeterManagement.
        /// </summary>
        public static string UserFunction_MeterManagement {
            get {
                return ResourceManager.GetString("UserFunction_MeterManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabMeterType.
        /// </summary>
        public static string UserFunction_MeterType {
            get {
                return ResourceManager.GetString("UserFunction_MeterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMissingMessage.
        /// </summary>
        public static string UserFunction_MissingMessage {
            get {
                return ResourceManager.GetString("UserFunction_MissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMissingMessageList.
        /// </summary>
        public static string UserFunction_MissingMessageList {
            get {
                return ResourceManager.GetString("UserFunction_MissingMessageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnMissingPE.
        /// </summary>
        public static string UserFunction_MissingPE {
            get {
                return ResourceManager.GetString("UserFunction_MissingPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnModemManagement.
        /// </summary>
        public static string UserFunction_ModemManagement {
            get {
                return ResourceManager.GetString("UserFunction_ModemManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mnOperation.
        /// </summary>
        public static string UserFunction_Operation {
            get {
                return ResourceManager.GetString("UserFunction_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin từ điểm đo này sang điểm đo kia.
        /// </summary>
        public static string UserFunction_ReplaceMeasurementPoint {
            get {
                return ResourceManager.GetString("UserFunction_ReplaceMeasurementPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabServer.
        /// </summary>
        public static string UserFunction_Server {
            get {
                return ResourceManager.GetString("UserFunction_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mnServerConnect.
        /// </summary>
        public static string UserFunction_ServerConnect {
            get {
                return ResourceManager.GetString("UserFunction_ServerConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabSoftwareVersion.
        /// </summary>
        public static string UserFunction_SoftwareVersion {
            get {
                return ResourceManager.GetString("UserFunction_SoftwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabSystemConfig.
        /// </summary>
        public static string UserFunction_SystemConfig {
            get {
                return ResourceManager.GetString("UserFunction_SystemConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabSystemHistories.
        /// </summary>
        public static string UserFunction_SystemHistories {
            get {
                return ResourceManager.GetString("UserFunction_SystemHistories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabTopics.
        /// </summary>
        public static string UserFunction_Topics {
            get {
                return ResourceManager.GetString("UserFunction_Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mnTopMenu.
        /// </summary>
        public static string UserFunction_TopMenu {
            get {
                return ResourceManager.GetString("UserFunction_TopMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin khách hàng.
        /// </summary>
        public static string UserFunction_UpdateCustomer {
            get {
                return ResourceManager.GetString("UserFunction_UpdateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin DCU.
        /// </summary>
        public static string UserFunction_UpdateDcu {
            get {
                return ResourceManager.GetString("UserFunction_UpdateDcu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin của điểm đo.
        /// </summary>
        public static string UserFunction_UpdateMeasurementPoint {
            get {
                return ResourceManager.GetString("UserFunction_UpdateMeasurementPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to btnUpdateMeasurementPoitInfo.
        /// </summary>
        public static string UserFunction_UpdateMeasurementPoitInfo {
            get {
                return ResourceManager.GetString("UserFunction_UpdateMeasurementPoitInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin công tơ.
        /// </summary>
        public static string UserFunction_UpdateMeter {
            get {
                return ResourceManager.GetString("UserFunction_UpdateMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabUserFunction.
        /// </summary>
        public static string UserFunction_UserFunction {
            get {
                return ResourceManager.GetString("UserFunction_UserFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UserFunction_UserManagem {
            get {
                return ResourceManager.GetString("UserFunction_UserManagem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tabUserManagement.
        /// </summary>
        public static string UserFunction_UserManagement {
            get {
                return ResourceManager.GetString("UserFunction_UserManagement", resourceCulture);
            }
        }
    }
}
